### ISSUE TITLE
Unable to post event to calagator

### ISSUE THREAD

**Issue by elizabethstock** [calagator/calagator.org#23] opened 2018-06-05 03:10 UTC
We tried to post and event: [https://www.eventbrite.com/e/pdx-women-in-tech-pdxwit-women-tech-summer-soiree-tickets-46660516862] on Calagator this morning but received an error about the content being blacklisted. We attempted to remove panelist names and a few other things but couldn't figure out what was causing the trigger. Please assist. Thank you!

**Comment by jhelwig** [comment] 2018-06-05 15:19
Narrowed it down to something in the following line of the description triggering the blacklisted content error:

```
Panelist representing virtual reality: Stephanie Mendoza, Unity Developer and WebVR Specialist, Portland Immersive Group
```

I'm not sure what in that specific line is triggering it, though. I tried previewing an event with just that content, and pulling out bits of it to see what it was that was triggering the error, but I wasn't able to narrow it down before I was forced to solve multiple captchas every time I wanted to preview the event.

**Comment by aeschright** [comment] 2019-05-01 19:56
Closing because we've been unable to verify the cause. If it happens again, please file another issue. Thanks!

**Closed by aeschright** 2019-05-01 19:56 UTC
